# - name: uninstall mariadb-server
#   become: true
#  ansible.builtin.apt:
#     name: mariadb*
#     state: absent
#     purge: true

- name: Set apt autoremove
  become: true
  ansible.builtin.apt:
    purge: true
    autoremove: true

- name: Install mysql-server
  become: true
  ansible.builtin.apt:
    name: [mysql-server, python3-pymysql]
  notify: restart_mysql

- name: Put mysql conf
  become: true
  ansible.builtin.copy:
    src: zz-isucon.cnf
    dest: /etc/mysql/mysql.conf.d/zz-isucon.cnf
  notify: restart_mysql

- name: Change systemd service unit for mysql
  become: true
  ini_file:
    path: /lib/systemd/system/mysql.service
    section: Service
    option: LimitNOFILE
    value: 65535
  notify: restart_mysql
