- name: Install dstat (alternative of netdata!)
  ansible.builtin.apt:
    name: dstat

- name: Check if /lib/systemd/system/netdata.service exists
  ansible.builtin.stat:
    path: /lib/systemd/system/netdata.service
  register: netdata_result

- name: Download install script for netdata
  ansible.builtin.get_url:
    url: https://my-netdata.io/kickstart-static64.sh
    dest: /tmp/netdata.sh
    mode: "0755"
  register: netdata
  when: not(netdata_result.stat.exists) and not(ansible_check_mode)

- name: Install netdata
  ansible.builtin.shell: true | /tmp/netdata.sh
  when: netdata.changed and not(ansible_check_mode)

- name: Put netdata mysql conf
  become: true
  ansible.builtin.copy:
    src: mysql.conf
    dest: /etc/netdata/go.d/mysql.conf
    mode: "0644"
