- name: Post_alp
  become: true
  ansible.builtin.command: discord.sh --file /tmp/alp.md --webhook-url="{{ discord_webhooks_url }}"

- name: Post_pt_query_digest
  become: true
  ansible.builtin.command: discord.sh --file /tmp/pt-query-digest.md --webhook-url="{{ discord_webhooks_url }}"
