- name: post_alp
  become: true
  command: discord.sh --file /tmp/alp.md --webhook-url="{{discord_webhooks_url}}"

- name: post_pt_query_digest
  become: true
  command: discord.sh --file /tmp/pt-query-digest.md --webhook-url="{{discord_webhooks_url}}"
